;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		evil-change
		evil-next-line
		evil-normal-state
		evil-previous-line
		save-some-buffers
		wgrep-finish-edit
		))

(setq mc/cmds-to-run-once
      '(
		compile
		evil-delete-backward-char-and-join
		evil-forward-char
		evil-mouse-drag-region
		evil-shell-command
		))
